import { createContext, useContext, type ReactNode } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, post } from "../../lib/api";
export type Actor = { id: string; organizationId: string; email: string; firstName: string; lastName: string | null; roles: Array<{ role: "EMPLOYEE" | "ADMIN" | "ASSET_MANAGER" | "DEPARTMENT_HEAD"; departmentId: string | null }> };
type AuthValue = { user: Actor | null; loading: boolean; login(values: { email: string; password: string }): Promise<void>; signup(values: { email: string; password: string; firstName: string; lastName?: string }): Promise<void>; logout(): Promise<void>; hasRole(...roles: string[]): boolean };
const AuthContext = createContext<AuthValue | null>(null);
export function AuthProvider({ children }: { children: ReactNode }) { const client = useQueryClient(); const me = useQuery({ queryKey: ["me"], queryFn: () => api<Actor>("/auth/me").then((r) => r.data), retry: false }); const loginMutation = useMutation({ mutationFn: (values: { email: string; password: string }) => post<Actor>("/auth/login", values).then((r) => r.data), onSuccess: (user) => client.setQueryData(["me"], user) }); const signupMutation = useMutation({ mutationFn: (values: { email: string; password: string; firstName: string; lastName?: string }) => post<Actor>("/auth/signup", values).then((r) => r.data), onSuccess: (user) => client.setQueryData(["me"], user) }); const logoutMutation = useMutation({ mutationFn: () => post<void>("/auth/logout", {}), onSuccess: () => { client.clear(); client.setQueryData(["me"], null); } }); const value: AuthValue = { user: me.data ?? null, loading: me.isLoading, login: async (v) => { await loginMutation.mutateAsync(v); }, signup: async (v) => { await signupMutation.mutateAsync(v); }, logout: async () => { await logoutMutation.mutateAsync(); }, hasRole: (...roles) => Boolean(me.data?.roles.some((role) => roles.includes(role.role))) }; return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>; }
export function useAuth() { const value = useContext(AuthContext); if (!value) throw new Error("AuthProvider is missing"); return value; }

