import type { AssetCondition } from "@prisma/client";
import { prisma, logActivity, notify } from "../../platform/trace/trace.service.js";
import { AppError } from "../../platform/http/errors.js";

export async function listAllocations(organizationId: string, activeOnly = false) { return prisma.allocation.findMany({ where: { organizationId, ...(activeOnly ? { endedAt: null } : {}) }, orderBy: { allocatedAt: "desc" } }); }
export async function getAllocation(id: string, organizationId: string) { const item = await prisma.allocation.findFirst({ where: { id, organizationId } }); if (!item) throw new AppError(404, "ALLOCATION_NOT_FOUND", "Allocation not found."); return item; }
export async function createAllocation(actorId: string, organizationId: string, requestId: string, input: { assetId: string; allocatedToUserId?: string; allocatedToDepartmentId?: string; expectedReturnAt?: string; checkoutCondition: AssetCondition; checkoutNotes?: string }) {
  return prisma.$transaction(async (tx) => {
    const asset = await tx.asset.findFirst({ where: { id: input.assetId, organizationId } }); if (!asset) throw new AppError(404, "ASSET_NOT_FOUND", "Asset not found."); if (asset.status !== "AVAILABLE") throw new AppError(409, "ASSET_NOT_AVAILABLE", `Asset is currently ${asset.status.toLowerCase().replaceAll("_", " ")}.`);
    if (input.allocatedToUserId) { const user = await tx.user.findFirst({ where: { id: input.allocatedToUserId, organizationId, status: "ACTIVE" } }); if (!user) throw new AppError(422, "INVALID_RECIPIENT", "Select an active employee."); }
    const allocation = await tx.allocation.create({ data: { organizationId, assetId: asset.id, allocatedToUserId: input.allocatedToUserId ?? null, allocatedToDepartmentId: input.allocatedToDepartmentId ?? null, allocatedByUserId: actorId, expectedReturnAt: input.expectedReturnAt ? new Date(input.expectedReturnAt) : null, checkoutCondition: input.checkoutCondition, checkoutNotes: input.checkoutNotes ?? null } });
    await tx.asset.update({ where: { id: asset.id }, data: { status: "ALLOCATED" } }); await tx.assetStatusHistory.create({ data: { organizationId, assetId: asset.id, fromStatus: asset.status, toStatus: "ALLOCATED", reasonCode: "ALLOCATED", sourceType: "ALLOCATION", sourceId: allocation.id, changedByUserId: actorId } });
    if (input.allocatedToUserId) await notify(tx, { organizationId, recipientUserId: input.allocatedToUserId, type: "ASSET_ASSIGNED", title: "Asset assigned", body: `${asset.assetTag} ${asset.name} was assigned to you.`, entityType: "ALLOCATION", entityId: allocation.id });
    await logActivity(tx, { organizationId, actorUserId: actorId, requestId, action: "ASSET_ALLOCATED", entityType: "ALLOCATION", entityId: allocation.id, summary: `Allocated ${asset.assetTag}.` }); return allocation;
  });
}
export async function requestReturn(actorId: string, organizationId: string, requestId: string, allocationId: string, input: { proposedCondition?: AssetCondition; requestNotes?: string }) { const allocation = await getAllocation(allocationId, organizationId); if (allocation.endedAt) throw new AppError(409, "ALLOCATION_ENDED", "This allocation has already ended."); const item = await prisma.returnRequest.create({ data: { organizationId, allocationId, requestedByUserId: actorId, proposedCondition: input.proposedCondition ?? null, requestNotes: input.requestNotes ?? null } }); await logActivity(prisma, { organizationId, actorUserId: actorId, requestId, action: "RETURN_REQUESTED", entityType: "RETURN_REQUEST", entityId: item.id, summary: "Requested an asset return." }); return item; }
export async function listReturns(organizationId: string) { return prisma.returnRequest.findMany({ where: { organizationId }, orderBy: { createdAt: "desc" } }); }
export async function decideReturn(actorId: string, organizationId: string, requestId: string, id: string, approve: boolean, input: { checkinCondition?: AssetCondition; checkinNotes?: string; decisionNotes?: string }) {
  return prisma.$transaction(async (tx) => { const request = await tx.returnRequest.findFirst({ where: { id, organizationId } }); if (!request) throw new AppError(404, "RETURN_NOT_FOUND", "Return request not found."); if (request.status !== "PENDING") throw new AppError(409, "RETURN_ALREADY_DECIDED", "This return request was already decided.");
    if (!approve) return tx.returnRequest.update({ where: { id }, data: { status: "REJECTED", decidedByUserId: actorId, decidedAt: new Date(), decisionNotes: input.decisionNotes ?? null } });
    if (!input.checkinCondition) throw new AppError(422, "CONDITION_REQUIRED", "Check-in condition is required."); const allocation = await tx.allocation.findFirst({ where: { id: request.allocationId, endedAt: null } }); if (!allocation) throw new AppError(409, "ALLOCATION_ENDED", "The allocation is no longer active.");
    await tx.allocation.update({ where: { id: allocation.id }, data: { endedAt: new Date(), endedByUserId: actorId, endReason: "RETURNED", checkinCondition: input.checkinCondition, checkinNotes: input.checkinNotes ?? null } }); await tx.asset.update({ where: { id: allocation.assetId }, data: { status: "AVAILABLE", condition: input.checkinCondition } });
    const updated = await tx.returnRequest.update({ where: { id }, data: { status: "APPROVED", decidedByUserId: actorId, decidedAt: new Date(), checkinCondition: input.checkinCondition, checkinNotes: input.checkinNotes ?? null, decisionNotes: input.decisionNotes ?? null } });
    if (allocation.allocatedToUserId) await notify(tx, { organizationId, recipientUserId: allocation.allocatedToUserId, type: "RETURN_APPROVED", title: "Return approved", body: "Your asset return was approved.", entityType: "RETURN_REQUEST", entityId: id }); await logActivity(tx, { organizationId, actorUserId: actorId, requestId, action: "RETURN_APPROVED", entityType: "RETURN_REQUEST", entityId: id, summary: "Approved asset return." }); return updated;
  });
}
export async function listTransfers(organizationId: string) { return prisma.transferRequest.findMany({ where: { organizationId }, orderBy: { createdAt: "desc" } }); }
export async function createTransfer(actorId: string, organizationId: string, requestId: string, input: { sourceAllocationId: string; toUserId?: string; toDepartmentId?: string; reason: string }) { const allocation = await getAllocation(input.sourceAllocationId, organizationId); if (allocation.endedAt) throw new AppError(409, "ALLOCATION_ENDED", "The source allocation is no longer active."); const item = await prisma.transferRequest.create({ data: { organizationId, assetId: allocation.assetId, sourceAllocationId: allocation.id, requestedByUserId: actorId, toUserId: input.toUserId ?? null, toDepartmentId: input.toDepartmentId ?? null, reason: input.reason } }); await logActivity(prisma, { organizationId, actorUserId: actorId, requestId, action: "TRANSFER_REQUESTED", entityType: "TRANSFER_REQUEST", entityId: item.id, summary: "Requested an asset transfer." }); return item; }
export async function decideTransfer(actorId: string, organizationId: string, requestId: string, id: string, decision: "APPROVED" | "REJECTED" | "CANCELLED", notes?: string) { return prisma.$transaction(async (tx) => { const request = await tx.transferRequest.findFirst({ where: { id, organizationId } }); if (!request) throw new AppError(404, "TRANSFER_NOT_FOUND", "Transfer request not found."); if (request.status !== "PENDING") throw new AppError(409, "TRANSFER_ALREADY_DECIDED", "This transfer request was already decided."); if (decision !== "APPROVED") return tx.transferRequest.update({ where: { id }, data: { status: decision, decidedByUserId: actorId, decidedAt: new Date(), decisionNotes: notes ?? null } });
    const source = await tx.allocation.findFirst({ where: { id: request.sourceAllocationId, endedAt: null } }); const asset = await tx.asset.findUnique({ where: { id: request.assetId } }); if (!source || !asset) throw new AppError(409, "SOURCE_ALLOCATION_CHANGED", "The source allocation is no longer active."); if (asset.status === "UNDER_MAINTENANCE") throw new AppError(409, "ASSET_UNDER_MAINTENANCE", "The asset cannot be transferred during maintenance.");
    await tx.allocation.update({ where: { id: source.id }, data: { endedAt: new Date(), endedByUserId: actorId, endReason: "TRANSFERRED" } }); const resulting = await tx.allocation.create({ data: { organizationId, assetId: source.assetId, allocatedToUserId: request.toUserId, allocatedToDepartmentId: request.toDepartmentId, allocatedByUserId: actorId, checkoutCondition: asset.condition } }); const updated = await tx.transferRequest.update({ where: { id }, data: { status: "APPROVED", decidedByUserId: actorId, decidedAt: new Date(), decisionNotes: notes ?? null, resultingAllocationId: resulting.id } });
    if (request.toUserId) await notify(tx, { organizationId, recipientUserId: request.toUserId, type: "TRANSFER_APPROVED", title: "Asset transferred", body: `${asset.assetTag} was transferred to you.`, entityType: "TRANSFER_REQUEST", entityId: id }); await logActivity(tx, { organizationId, actorUserId: actorId, requestId, action: "TRANSFER_APPROVED", entityType: "TRANSFER_REQUEST", entityId: id, summary: `Transferred ${asset.assetTag}.` }); return updated;
  }); }

