import { prisma } from "../../platform/database/prisma.js"; import { AppError } from "../../platform/http/errors.js";
export const reportNames = ["department-allocation-summary", "asset-status-summary", "allocation-utilization", "booking-utilization", "most-used-assets", "most-used-resources", "idle-assets", "maintenance-frequency", "open-aging-maintenance", "assets-nearing-retirement", "booking-count-by-resource"] as const; export type ReportName = typeof reportNames[number];
const minutes = (start: Date, end: Date) => Math.max(0, (end.getTime() - start.getTime()) / 60_000); const overlapMinutes = (start: Date, end: Date | null, from: Date, to: Date) => minutes(new Date(Math.max(start.getTime(), from.getTime())), new Date(Math.min((end ?? to).getTime(), to.getTime())));
export function reportingWindow(from?: string, to?: string) { const end = to ? new Date(to) : new Date(); const start = from ? new Date(from) : new Date(end.getTime() - 90 * 86_400_000); if (!Number.isFinite(start.getTime()) || !Number.isFinite(end.getTime()) || start >= end) throw new AppError(422, "INVALID_REPORTING_WINDOW", "Choose a valid reporting date range."); return { start, end }; }
export async function runReport(name: ReportName, organizationId: string, from?: string, to?: string) { const { start, end } = reportingWindow(from, to); const assets = await prisma.asset.findMany({ where: { organizationId } }); const assetMap = new Map(assets.map((item) => [item.id, item]));
  if (name === "asset-status-summary") return (await prisma.asset.groupBy({ by: ["status"], where: { organizationId }, _count: true })).map((row) => ({ status: row.status, count: row._count }));
  if (name === "department-allocation-summary") { const rows = await prisma.allocation.groupBy({ by: ["allocatedToDepartmentId"], where: { organizationId, endedAt: null }, _count: true }); const departments = await prisma.department.findMany({ where: { organizationId } }); return rows.map((row) => ({ department: departments.find((d) => d.id === row.allocatedToDepartmentId)?.name ?? "Employee custody", activeAllocations: row._count })); }
  const allocations = await prisma.allocation.findMany({ where: { organizationId, allocatedAt: { lt: end }, OR: [{ endedAt: null }, { endedAt: { gt: start } }] } });
  if (name === "allocation-utilization") { const allocated = allocations.reduce((sum, row) => sum + overlapMinutes(row.allocatedAt, row.endedAt, start, end), 0); const available = assets.filter((asset) => !["LOST", "RETIRED", "DISPOSED"].includes(asset.status)).length * minutes(start, end); return [{ allocatedMinutes: Math.round(allocated), inServiceMinutes: Math.round(available), utilizationPercent: available ? Number((allocated / available * 100).toFixed(2)) : 0 }]; }
  if (name === "most-used-assets") { const totals = new Map<string, number>(); for (const row of allocations) totals.set(row.assetId, (totals.get(row.assetId) ?? 0) + overlapMinutes(row.allocatedAt, row.endedAt, start, end)); return [...totals].map(([id, total]) => ({ assetTag: assetMap.get(id)?.assetTag, assetName: assetMap.get(id)?.name, allocatedMinutes: Math.round(total) })).sort((a, b) => b.allocatedMinutes - a.allocatedMinutes); }
  const bookings = await prisma.booking.findMany({ where: { organizationId, status: { in: ["CONFIRMED", "COMPLETED"] }, startAt: { lt: end }, endAt: { gt: start } } });
  if (name === "booking-utilization") { const booked = bookings.reduce((sum, row) => sum + overlapMinutes(row.startAt, row.endAt, start, end), 0); const profiles = await prisma.resourceProfile.count({ where: { organizationId } }); const capacity = profiles * minutes(start, end); return [{ confirmedMinutes: Math.round(booked), configuredBookableMinutes: Math.round(capacity), utilizationPercent: capacity ? Number((booked / capacity * 100).toFixed(2)) : 0 }]; }
  if (name === "most-used-resources") { const totals = new Map<string, number>(); for (const row of bookings) totals.set(row.assetId, (totals.get(row.assetId) ?? 0) + overlapMinutes(row.startAt, row.endAt, start, end)); return [...totals].map(([id, total]) => ({ assetTag: assetMap.get(id)?.assetTag, resource: assetMap.get(id)?.name, confirmedMinutes: Math.round(total) })).sort((a, b) => b.confirmedMinutes - a.confirmedMinutes); }
  if (name === "booking-count-by-resource") { const totals = new Map<string, number>(); for (const row of bookings) totals.set(row.assetId, (totals.get(row.assetId) ?? 0) + 1); return [...totals].map(([id, count]) => ({ assetTag: assetMap.get(id)?.assetTag, resource: assetMap.get(id)?.name, bookingCount: count })).sort((a, b) => b.bookingCount - a.bookingCount); }
  if (name === "idle-assets") { const since = new Date(Date.now() - 60 * 86_400_000); const activeIds = new Set([...(await prisma.allocation.findMany({ where: { organizationId, OR: [{ endedAt: null }, { allocatedAt: { gte: since } }] }, select: { assetId: true } })).map((r) => r.assetId), ...(await prisma.booking.findMany({ where: { organizationId, status: { in: ["CONFIRMED", "COMPLETED"] }, endAt: { gte: since } }, select: { assetId: true } })).map((r) => r.assetId)]); return assets.filter((asset) => asset.status === "AVAILABLE" && !activeIds.has(asset.id) && (asset.acquisitionDate ?? asset.createdAt) < since).map((asset) => ({ assetTag: asset.assetTag, assetName: asset.name, idleSince: (asset.acquisitionDate ?? asset.createdAt).toISOString() })); }
  const maintenance = await prisma.maintenanceRequest.findMany({ where: { organizationId } });
  if (name === "open-aging-maintenance") return maintenance.filter((item) => !["RESOLVED", "REJECTED", "CANCELLED"].includes(item.status)).map((item) => { const days = Math.floor((Date.now() - item.createdAt.getTime()) / 86_400_000); return { assetTag: assetMap.get(item.assetId)?.assetTag, status: item.status, ageDays: days, ageBucket: days < 8 ? "0-7 days" : days < 31 ? "8-30 days" : "31+ days" }; });
  if (name === "maintenance-frequency") { const categories = await prisma.assetCategory.findMany({ where: { organizationId } }); const counts = new Map<string, number>(); for (const item of maintenance.filter((m) => m.createdAt >= start && m.createdAt <= end)) { const categoryId = assetMap.get(item.assetId)?.categoryId; if (categoryId) counts.set(categoryId, (counts.get(categoryId) ?? 0) + 1); } return [...counts].map(([id, count]) => ({ category: categories.find((c) => c.id === id)?.name, requestCount: count })); }
  if (name === "assets-nearing-retirement") { const threshold = new Date(Date.now() + 90 * 86_400_000); const categories = new Map((await prisma.assetCategory.findMany({ where: { organizationId } })).map((c) => [c.id, c])); return assets.filter((asset) => { if (asset.expectedRetirementOn) return asset.expectedRetirementOn <= threshold; const months = categories.get(asset.categoryId)?.defaultUsefulLifeMonths; const base = asset.acquisitionDate; return Boolean(months && base && new Date(base.getTime() + months * 30.4375 * 86_400_000) <= threshold); }).map((asset) => ({ assetTag: asset.assetTag, assetName: asset.name, expectedRetirementOn: asset.expectedRetirementOn?.toISOString() ?? "Derived from useful life" })); }
  throw new AppError(404, "REPORT_NOT_FOUND", "Report not found."); }
export function toCsv(rows: Array<Record<string, unknown>>) { if (!rows.length) return "No data\n"; const headers = Object.keys(rows[0]!); const cell = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`; return `${headers.map(cell).join(",")}\n${rows.map((row) => headers.map((header) => cell(row[header])).join(",")).join("\n")}\n`; }

